### ISSUE TITLE
[特性请求] 支持文件强制覆盖规则

### ISSUE THREAD

**Issue by SettingDust** [BalloonUpdate/McPatchManage#2]
可以在一个补丁里添加一个类似 gitignore 的文件，让一些文件被强制覆盖

**Comment by asforest** [comment]
加入开发日程了

目前有个变通方法：可以在前一个版本里将这个文件删除，然后在后一个版本里再添加这个文件的方式来实现强制覆盖

**Comment by SettingDust** [comment]
> 加入开发日程了
> 
> 目前有个变通方法：可以在前一个版本里将这个文件删除，然后在后一个版本里再添加这个文件的方式来实现强制覆盖

玩家修改了的也可以吗？

**Comment by asforest** [comment]
删除修改都可以，这种方法文档里有提及过

**Comment by SettingDust** [comment]
请说明一下关闭的原因？ @Mr-Ao-Dragon

**Comment by Mr-Ao-Dragon** [comment]
> 请说明一下关闭的原因？ @Mr-Ao-Dragon
抱歉，我在编译测试的时候看到了没写完的功能，误以为已经做好了，已经重新打开issue,我的错

**Comment by asforest** [comment]
1.1.8版本里加入了这个功能，现在可以试试了。 大致的用法是创建一个`overwrites.txt`的文件，把要强制更新的文件路径一行行写进去（只能写具体文件，写目录是没效果的）。启动管理端后，用c指令或者s只能都可以看到效果：匹配的文件名后面会有`（强制覆盖）`的字样。

https://github.com/BalloonUpdate/McPatchManage/releases/tag/v1.1.8

![image](https://github.com/BalloonUpdate/McPatchManage/assets/28993050/a7730db8-bad4-4722-b425-65c27fd33bff)

**Comment by SettingDust** [comment]
> 只能写具体文件，写目录是没效果的

glob 可以吗

**Comment by asforest** [comment]
glob暂时不会做。用到强制覆盖功能的人太少了，暂不考虑做进一步的开发。

**Comment by asforest** [comment]
不过有个变通办法：用脚本手动删除历史目录下的对应文件，也可以触发强制更新

**Comment by asforest** [comment]
强制覆盖规则已经开发完毕，所以这个issue先关闭了。
如果一定要glob表达式的支持可以专门开一个新的issue

**Comment by asforest** [comment]
1.1.10版本已经支持Glob表达式
