### ISSUE TITLE
打包出来的 zip 有问题，二进制全错了

### ISSUE THREAD

**Issue by SettingDust** [BalloonUpdate/McPatchManage#4]
复现，打开 public 里的 zip 里的任一文件，正确内容应该是 `aaa`
[McPatchManage-1.1.7.zip](https://github.com/BalloonUpdate/McPatchManage/files/11496171/McPatchManage-1.1.7.zip)

**Comment by asforest** [comment]
`h91AY&SY`是bzip压缩算法的识别头。更新包存储的是压缩后的数据，并未直接存储源数据。外面的zip格式只是个封装，不起压缩的作用

**Comment by SettingDust** [comment]
客户端更新之后文件也是错误的，不是全部错误，有点奇怪

**Comment by SettingDust** [comment]
不对，应该是全部错误，lib 是 hmcl 下载的，上午还是好的，下午更新就坏了
![图片](https://github.com/BalloonUpdate/McPatchManage/assets/19922286/d0019c49-93d6-46ee-b4a2-fd1f10fd2525)
![图片](https://github.com/BalloonUpdate/McPatchManage/assets/19922286/111b3c75-8950-40ec-ab40-e68aec307046)

**Comment by asforest** [comment]
还有更多信息吗？我在本地测试了下你发我的zip文件，没能复现这个问题。

最好是能有出现这个报错当时的McPatchClient日志（日志应该都覆盖了吧）

如果要紧急修复这些文件，可以把出错的文件删掉后打包，然后在下个版本里加回去，客户端就可以重新下载完整数据了（只是流量消耗很大，看情况使用）

**Comment by SettingDust** [comment]
我打包了两次都是这个报错

**Comment by asforest** [comment]
方便提供一下相关的更新包文件吗

**Comment by SettingDust** [comment]
> 方便提供一下相关的更新包文件吗

已经发到邮箱

**Comment by asforest** [comment]
收到了，这个更新包文件就是会出问题的那个吗？

**Comment by SettingDust** [comment]
> 收到了，这个更新包文件就是会出问题的那个吗？

是的，是不能复现吗？

**Comment by asforest** [comment]
能复现了。这个是用1.1.6还是1.1.7版本打包出来的？

**Comment by SettingDust** [comment]
1.1.6 打包的 1.0.8，1.1.7 打包的 1.0.9（被我删了）都这样

**Comment by asforest** [comment]
明白了，感谢。我排查一下问题

**Comment by SettingDust** [comment]
我想起来了，第一次可能是我的文件有问题，这个错误是在上午我测试那个问题之后出现的，因为 history 没了，我就 combine 了一下，然后解压了打包的 zip 去当作 history，然后我最新的内容到了 workspace 之后，我发现变更列表很大，但是我没管，继续生成了
但是按逻辑说我的 workspace 会覆盖掉之前的不正确的二进制，但是事实上没有，我的 history 和 workspace 现在都是正确的文件内容

**Comment by asforest** [comment]
> 然后解压了打包的 zip 去当作 history

嗯，我感觉这一步很有可能会出错，打包的zip里记录的不一定是完整的原始数据

**Comment by SettingDust** [comment]
combine 之后，我解压出来的应该是 bzip 之后的二进制，但是我的 workspace 是正确的，不应该这样吧？

**Comment by SettingDust** [comment]
我本地还留存我之前打包的 1.0.9，要看看吗

**Comment by SettingDust** [comment]
或者我现在再删除 history 打包一个试试

**Comment by asforest** [comment]
> combine 之后，我解压出来的应该是 bzip 之后的二进制，但是我的 workspace 是正确的，不应该这样吧？

workspace 和 history 有一个出错最后打包出来的结果就是错误的。不应该手动解压更新包，管理端有指令可以自动解压和还原的命令，是revert还是restore我记不清了。

把 1.0.9 的 .mcpatch-meta.json 文件发我就行不用发整个更新包

补充一下：打包过程里有个校验的步骤，你的1.0.8能过校验就说明打包过程应该是没问题的，我感觉像是history目录下的数据错乱对最终的结果造成了影响

**Comment by SettingDust** [comment]
http://dl.adogsama.moe/files/6464abd730538/mcpatch-meta.json

**Comment by SettingDust** [comment]
https://tmp.link/f/6464abc781956

**Comment by SettingDust** [comment]
那就是理论上我移除 history 重新生成一下就好了

**Comment by asforest** [comment]
对的
---
另外1.0.9 的 .mcpatch-meta.json 文件看不出来有什么问题

**Comment by SettingDust** [comment]
在试了，1.0.9 就是删除之后打包的，有问题吗？

**Comment by SettingDust** [comment]
那就奇怪了，我更新之后还是说报错，可能是他没更新到吧

**Comment by asforest** [comment]
这样。你随便找一个1.0.9更新包里的文件解压出来算sha1，如果能和meta.json里的bizippped-hash对上，就说明打包过程本身是没问题的

![image](https://github.com/BalloonUpdate/McPatchManage/assets/28993050/46dbf7ad-ddf2-4233-99c1-eb4ae1c78c0a)

**Comment by asforest** [comment]
哦对了，可以直接在管理端用t这个命令来测试，不用解压这么麻烦
