### ISSUE TITLE
打包后的文本文件全部乱码

### ISSUE THREAD

**Issue by ddaodan** [BalloonUpdate/McPatchManage#7]
1.1.12版本
出现这个问题后，我用clear清空了history和public文件夹，但是打包后的文件里文本文件都是乱码
以下为我单独打包的测试包
[test.mcpatch.zip](https://github.com/BalloonUpdate/McPatchManage/files/12252855/test.mcpatch.zip)
里面只有一个test.txt，打开是乱码的
history文件夹里的文件是正常的
验证所有版本文件能通过

**Comment by asforest** [comment]
test.mcpatch.zip 打不开，提示AccessDenied, Request has expired

---

又能打开了，真奇怪

**Comment by asforest** [comment]
并未乱码

![image](https://github.com/BalloonUpdate/McPatchManage/assets/28993050/07b51a67-0ef7-4b2a-b6cc-ca82f35fc5f8)

**Comment by asforest** [comment]
zip包里的文件均使用bzip算法压缩过，直接查看就是乱码的。`h91AY&SY`是bzip压缩算法的识别头。所有以它打头的文件都是bzip压缩过的

![image](https://github.com/BalloonUpdate/McPatchManage/assets/28993050/022a2697-0bab-46f0-aad3-645f97b89bb1)

**Comment by ddaodan** [comment]
稍等，我重新准备一下测试环境
发现这个问题是因为在之前的一次合并包后，有一部分玩家更新会提示 配置文件损坏，而我的更新包里是有配置文件的，文件打开就是乱码的

**Comment by asforest** [comment]
有没有删除过更新包文件

**Comment by ddaodan** [comment]
没有，本地只进行过合并包

我这里成功复现了，添加这个更新源：
`https://pan.ddaodan.cn/d/Download/Minecraft/update`
更新后mc-patch-config.yml会变成乱码文件
[更新包文件地址](https://pan.ddaodan.cn/d/Download/Minecraft/update/0.3.mcpatch.zip)

我重置了工作区后重新打包，就没有问题了，估计是合并包的时候出的问题

**Comment by asforest** [comment]
很奇怪，只有`mc-patch-config.yml`是乱码的，别的文件都是正常的。你有没有把更新包里面的`mc-patch-config.yml`解压出来丢进工作空间目录或者历史目录里过？

**Comment by ddaodan** [comment]
没有，一直都没动过

**Comment by asforest** [comment]
这个问题完整的复现流程是什么

**Comment by ddaodan** [comment]
目前不是很清楚，我做过的操作只有合并包，这个包是第三次合并包合并出来的，也就是这次合并之后出现了问题

**Comment by asforest** [comment]
好，我再排查一下代码

**Comment by asforest** [comment]
找到问题了，所有更新包中涉及修改的文件(Modify格式保存）的时候就会触发这个问题，已经在新的1.1.13中修复了
[releases/tag/v1.1.13](https://github.com/BalloonUpdate/McPatchManage/releases/tag/v1.1.13)

**Comment by ddaodan** [comment]
感谢，不过这个问题我也不知道是怎么触发的，我这里没法测试

**Comment by asforest** [comment]
正常使用就可以触发。当更新包里记录的不是完整数据，是文件差异数据的时候就会触发。概率还是挺大的，估计合并更新包大家都用的少，所以这个问题直到现在才被发现

**Comment by ddaodan** [comment]
最近暂时不需要合并包，没法测试，我先关掉了
